/**
 * @kailash/prism-compiler — TypeScript emitter for the codegen PoC
 *
 * Consumes a `ComponentSpecAst` and emits TypeScript source declaring the
 * adapter interface. Output is types-only; no runtime code.
 *
 * Scope of this PoC:
 *   - Emits the adapter `interface` with its generic type parameters.
 *   - Each method in `adapter.methods[]` becomes a property on the
 *     interface; the method's `signature:` string from the YAML is
 *     interpolated verbatim into the property type, preceded by the
 *     YAML `purpose:` string as JSDoc.
 *   - Optional methods (`required: false`) are emitted with a trailing
 *     `?` on the property name.
 *   - `support_types:` is emitted as a comment listing the types the
 *     adapter references; the emitter does NOT generate bodies for
 *     those types — they remain hand-written in `web/src/engines/<engine>/types.ts`.
 *     See docs/guides/codegen-architecture.md § "What gets generated".
 *
 * Conservative choice: the PoC treats `signature:` as opaque TypeScript
 * source and interpolates it directly. It does NOT parse signatures into
 * parameter lists / return types. Two consequences:
 *   1. The YAML's signature string MUST already be valid TypeScript —
 *      any error there becomes a compile error in the generated file.
 *   2. The emitter is portable to other platforms only insofar as the
 *      signature string is portable. A Dart emitter would need either a
 *      Dart-native signature field in the YAML or a real signature
 *      parser. See codegen-architecture.md § "Flutter output" for the
 *      chosen path.
 */
import { CodegenError, type CodegenOutputFile, type EmitContext, type MethodSpec } from './types.js';

/** Emit TypeScript for a single component spec. Returns one
 *  `OutputFile` — path is the adapter's name in kebab-case with a
 *  `-spec.ts` suffix. Caller decides where to write it. */
export function emitAdapterTypes(ctx: EmitContext): CodegenOutputFile {
  const { spec, sourcePath } = ctx;
  if (!spec.adapter) {
    throw new CodegenError(
      'NO_ADAPTER_IN_SPEC',
      `Component ${spec.name} has no adapter: section — nothing to emit`,
      sourcePath,
    );
  }
  const adapter = spec.adapter;

  const typeParamList = renderTypeParameters(adapter.type_parameters);
  const typeParamDocs = renderTypeParameterDocs(adapter.type_parameters);

  const methodDecls = adapter.methods.map(renderMethod).join('\n\n');

  const supersedesTag = adapter.supersedes
    ? `\n * @supersedes ${adapter.supersedes}`
    : '';

  const supportTypesNote =
    adapter.support_types.length > 0
      ? `\n// Support types referenced by this adapter (hand-written in web/src/engines/<engine>/types.ts):\n` +
        adapter.support_types.map((t) => `//   - ${t}`).join('\n') +
        '\n'
      : '';

  const content = `/**
 * ${adapter.name} — GENERATED from ${relativeSourcePath(sourcePath)}
 *
 * ${spec.description}
 *
 * This file is auto-generated by @kailash/prism-compiler (codegen PoC).
 * DO NOT EDIT BY HAND — regenerate via:
 *   npm --prefix compiler run codegen
 *
 * @spec        ${spec.name} v${spec.version}
 * @authority   ${adapter.authority}
 * @since       ${adapter.version_introduced}${supersedesTag}
 */
${supportTypesNote}
${typeParamDocs}export interface ${adapter.name}${typeParamList} {
${methodDecls}
}
`;

  return {
    path: `${toKebabCase(adapter.name)}-spec.ts`,
    content,
  };
}

function renderTypeParameters(
  params: ReadonlyArray<{ readonly name: string; readonly default?: string }>,
): string {
  if (params.length === 0) return '';
  const rendered = params
    .map((p) => (p.default ? `${p.name} = ${p.default}` : p.name))
    .join(', ');
  return `<${rendered}>`;
}

function renderTypeParameterDocs(
  params: ReadonlyArray<{
    readonly name: string;
    readonly default?: string;
    readonly description: string;
  }>,
): string {
  if (params.length === 0) return '';
  const lines = params.map((p) => ` * @typeParam ${p.name} — ${p.description}`);
  return `/**\n${lines.join('\n')}\n */\n`;
}

function renderMethod(method: MethodSpec): string {
  const optional = method.required ? '' : '?';
  const jsdoc = renderMethodJsDoc(method);
  return `${jsdoc}  readonly ${method.name}${optional}: ${method.signature};`;
}

function renderMethodJsDoc(method: MethodSpec): string {
  const lines = [
    '  /**',
    `   * ${method.purpose}`,
    method.required ? '   *' : '   *',
    `   * @required ${method.required ? 'true' : 'false'}`,
    '   */',
  ];
  return lines.join('\n') + '\n';
}

function toKebabCase(pascal: string): string {
  return pascal.replace(/([a-z])([A-Z])/g, '$1-$2').toLowerCase();
}

function relativeSourcePath(absolute: string): string {
  // Best-effort trim to `specs/components/<name>.yaml` without pulling
  // in `path.relative` against a cwd that may differ between CLI and
  // tests. Consumers just want a stable, readable attribution string.
  const idx = absolute.indexOf('specs/');
  return idx >= 0 ? absolute.slice(idx) : absolute;
}
