/**
 * @kailash/prism-compiler — Flutter target emitter
 * Generates ThemeData and Dart constants from theme tokens.
 * Spec: docs/specs/02-token-architecture.md § Compilation Targets
 */

import type { ThemeTokens, OutputFile } from './types.js';

function hexToFlutterColor(hex: string): string {
  const clean = hex.replace('#', '');
  return `Color(0xFF${clean.toUpperCase()})`;
}

function camelCase(str: string): string {
  return str.replace(/[-_.](\w)/g, (_, c: string) => c.toUpperCase());
}

/**
 * Generate Dart constants file with all primitive and semantic tokens.
 */
export function emitDartConstants(tokens: ThemeTokens): OutputFile {
  const lines: string[] = [
    '// Auto-generated by @kailash/prism-compiler',
    `// Theme: ${tokens.name}`,
    '// DO NOT EDIT — regenerate with: npx prism-compile --theme enterprise --target flutter',
    '',
    "import 'dart:ui';",
    '',
    '/// Primitive color tokens',
    'abstract final class PrismColors {',
  ];

  // Primitive colors
  for (const [name, hex] of Object.entries(tokens.tokens.primitive.color)) {
    const dartName = camelCase(name);
    lines.push(`  static const ${dartName} = ${hexToFlutterColor(hex)};`);
  }
  lines.push('}');
  lines.push('');

  // Spacing constants
  lines.push('/// Spacing scale');
  lines.push('abstract final class PrismSpacing {');
  for (const val of tokens.tokens.primitive.spacing.scale) {
    lines.push(`  static const double s${val} = ${val}.0;`);
  }
  lines.push('}');
  lines.push('');

  // Typography constants
  lines.push('/// Typography scale');
  lines.push('abstract final class PrismTypography {');
  const fontSizes = tokens.tokens.primitive.typography.scale ?? tokens.tokens.primitive.typography.sizes ?? [];
  for (const val of fontSizes) {
    lines.push(`  static const double size${val} = ${val}.0;`);
  }
  lines.push('');
  for (const val of tokens.tokens.primitive.typography.weights) {
    lines.push(`  static const FontWeight w${val} = FontWeight.w${val};`);
  }
  lines.push('}');
  lines.push('');

  // Radius constants
  lines.push('/// Border radius scale');
  lines.push('abstract final class PrismRadius {');
  for (const val of tokens.tokens.primitive.radius.scale) {
    if (val === 9999) {
      lines.push(`  static const double pill = ${val}.0;`);
    } else {
      lines.push(`  static const double r${val} = ${val}.0;`);
    }
  }
  lines.push('}');
  lines.push('');

  // Motion constants
  lines.push('/// Motion durations');
  lines.push('abstract final class PrismMotion {');
  for (const dur of tokens.tokens.primitive.motion.durations) {
    lines.push(`  static const Duration d${dur} = Duration(milliseconds: ${dur});`);
  }
  lines.push('}');
  lines.push('');

  // Breakpoints
  lines.push('/// Responsive breakpoints');
  lines.push('abstract final class PrismBreakpoints {');
  for (const [name, value] of Object.entries(tokens.tokens.primitive.breakpoints)) {
    lines.push(`  static const double ${name} = ${value}.0;`);
  }
  lines.push('}');

  return { path: 'prism_tokens.dart', content: lines.join('\n') + '\n' };
}

/**
 * Generate Flutter ThemeData from semantic tokens.
 */
export function emitThemeData(tokens: ThemeTokens): OutputFile {
  const { semantic, primitive } = tokens.tokens;

  const lines: string[] = [
    '// Auto-generated by @kailash/prism-compiler',
    `// Theme: ${tokens.name}`,
    '// DO NOT EDIT — regenerate with: npx prism-compile --theme enterprise --target flutter',
    '',
    "import 'package:flutter/material.dart';",
    "import 'prism_tokens.dart';",
    '',
    '/// Light theme generated from design tokens',
    'ThemeData prismLightTheme() {',
    '  return ThemeData(',
    '    useMaterial3: true,',
    '    brightness: Brightness.light,',
  ];

  // ColorScheme from semantic tokens (resolve $primitive references)
  const colorEntries = semantic.color;
  const primColors = primitive.color;
  const primary = getSemanticColorValue(colorEntries, 'interactive.primary', primColors);
  const error = getSemanticColorValue(colorEntries, 'status.error', primColors);
  const surface = getSemanticColorValue(colorEntries, 'surface.page', primColors);
  const onSurface = getSemanticColorValue(colorEntries, 'text.primary', primColors);

  lines.push('    colorScheme: ColorScheme.light(');
  if (primary) lines.push(`      primary: ${hexToFlutterColor(primary)},`);
  if (error) lines.push(`      error: ${hexToFlutterColor(error)},`);
  if (surface) lines.push(`      surface: ${hexToFlutterColor(surface)},`);
  if (onSurface) lines.push(`      onSurface: ${hexToFlutterColor(onSurface)},`);
  lines.push('    ),');

  // Typography from semantic tokens
  const sansFamily = primitive.typography.families.sans || 'Inter';
  const monoFamily = primitive.typography.families.mono || 'JetBrains Mono';

  lines.push(`    fontFamily: '${sansFamily.split(',')[0].replace(/['"]/g, '').trim()}',`);

  // TextTheme
  lines.push('    textTheme: const TextTheme(');
  const typMap: Record<string, string> = {
    'heading.h1': 'headlineLarge',
    'heading.h2': 'headlineMedium',
    'heading.h3': 'headlineSmall',
    'heading.h4': 'titleLarge',
    'body.default': 'bodyLarge',
    'body.small': 'bodyMedium',
    'caption': 'bodySmall',
    'label': 'labelLarge',
  };

  for (const [tokenPath, materialName] of Object.entries(typMap)) {
    const typ = getNestedValue(semantic.typography, tokenPath) as {
      size: number; weight: number; line_height: number;
    } | undefined;
    if (typ) {
      lines.push(`      ${materialName}: TextStyle(`);
      lines.push(`        fontSize: ${typ.size}.0,`);
      lines.push(`        fontWeight: FontWeight.w${typ.weight},`);
      lines.push(`        height: ${typ.line_height},`);
      lines.push('      ),');
    }
  }
  lines.push('    ),');

  lines.push('  );');
  lines.push('}');
  lines.push('');

  // Dark theme
  lines.push('/// Dark theme generated from design tokens');
  lines.push('ThemeData prismDarkTheme() {');
  lines.push('  return ThemeData(');
  lines.push('    useMaterial3: true,');
  lines.push('    brightness: Brightness.dark,');

  if (tokens.themes?.dark) {
    const darkColors = tokens.themes.dark.color || {};
    const resolveDark = (key: string): string | undefined => {
      const val = darkColors[key];
      if (val?.startsWith('$primitive.color.')) {
        return primitive.color[val.replace('$primitive.color.', '')] ?? val;
      }
      return val;
    };
    const darkPrimary = resolveDark('interactive.primary');
    const darkError = resolveDark('status.error');
    const darkSurface = resolveDark('surface.page');
    const darkOnSurface = resolveDark('text.primary');

    lines.push('    colorScheme: ColorScheme.dark(');
    if (darkPrimary) lines.push(`      primary: ${hexToFlutterColor(darkPrimary)},`);
    if (darkError) lines.push(`      error: ${hexToFlutterColor(darkError)},`);
    if (darkSurface) lines.push(`      surface: ${hexToFlutterColor(darkSurface)},`);
    if (darkOnSurface) lines.push(`      onSurface: ${hexToFlutterColor(darkOnSurface)},`);
    lines.push('    ),');
  }

  lines.push(`    fontFamily: '${sansFamily.split(',')[0].replace(/['"]/g, '').trim()}',`);
  lines.push('  );');
  lines.push('}');

  return { path: 'prism_theme.dart', content: lines.join('\n') + '\n' };
}

function getSemanticColorValue(
  colors: Record<string, unknown>,
  path: string,
  primitiveColors?: Record<string, string>,
): string | undefined {
  const val = getNestedValue(colors, path);
  let raw: string | undefined;
  if (typeof val === 'string') raw = val;
  else if (val && typeof val === 'object' && 'value' in val) {
    raw = (val as { value: string }).value;
  }

  // Resolve $primitive.color.{name} references to hex values
  if (raw?.startsWith('$primitive.color.') && primitiveColors) {
    const colorName = raw.replace('$primitive.color.', '');
    return primitiveColors[colorName] ?? raw;
  }
  return raw;
}

function getNestedValue(obj: Record<string, unknown>, path: string): unknown {
  const parts = path.split('.');
  let current: unknown = obj;
  for (const part of parts) {
    if (current == null || typeof current !== 'object') return undefined;
    current = (current as Record<string, unknown>)[part];
  }
  return current;
}

export function compileFlutter(tokens: ThemeTokens): OutputFile[] {
  return [emitDartConstants(tokens), emitThemeData(tokens)];
}
