/**
 * @kailash/prism-compiler — Project scaffolding
 * Generates a new Prism project with tokens, templates, and starter page.
 *
 * Usage: npx prism-scaffold --name my-app --theme enterprise
 */

import { mkdirSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';
import type { CompileTarget } from './types.js';

export interface ScaffoldOptions {
  name: string;
  theme: string;
  target: CompileTarget;
  outDir: string;
  template: string;
}

export interface ScaffoldResult {
  files: Array<{ path: string; description: string }>;
  errors: string[];
}

export function scaffold(options: ScaffoldOptions): ScaffoldResult {
  const { name, theme, target, outDir, template } = options;
  const files: ScaffoldResult['files'] = [];
  const errors: string[] = [];

  if (target === 'flutter') {
    errors.push('Flutter scaffolding not yet implemented. Use --target web.');
    return { files, errors };
  }

  const kebabName = name.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, '');

  // package.json
  const packageJson = {
    name: kebabName,
    version: '0.1.0',
    private: true,
    type: 'module',
    scripts: {
      dev: 'vite',
      build: 'tsc -b && vite build',
      preview: 'vite preview',
    },
    dependencies: {
      '@kailash/prism-web': '^0.1.0',
      react: '^19.1.0',
      'react-dom': '^19.1.0',
    },
    devDependencies: {
      '@kailash/prism-compiler': '^0.1.0',
      '@types/react': '^19.1.0',
      '@types/react-dom': '^19.1.0',
      '@vitejs/plugin-react': '^4.5.0',
      typescript: '^5.8.0',
      vite: '^6.3.0',
    },
  };
  files.push({ path: 'package.json', description: 'Project manifest' });

  // tsconfig.json
  const tsconfig = {
    compilerOptions: {
      target: 'ES2022',
      module: 'ESNext',
      moduleResolution: 'bundler',
      lib: ['ES2022', 'DOM', 'DOM.Iterable'],
      jsx: 'react-jsx',
      strict: true,
      noUncheckedIndexedAccess: true,
      outDir: 'dist',
      rootDir: 'src',
      skipLibCheck: true,
      forceConsistentCasingInFileNames: true,
      isolatedModules: true,
      resolveJsonModule: true,
    },
    include: ['src/**/*'],
    exclude: ['node_modules', 'dist'],
  };
  files.push({ path: 'tsconfig.json', description: 'TypeScript config (strict)' });

  // vite.config.ts
  const viteConfig = `import { defineConfig } from 'vite';
import react from '@vitejs/plugin-react';

export default defineConfig({
  plugins: [react()],
});
`;
  files.push({ path: 'vite.config.ts', description: 'Vite dev server config' });

  // index.html
  const indexHtml = `<!doctype html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>${name}</title>
    <link rel="stylesheet" href="/src/tokens.css" />
    <style>
      *, *::before, *::after { box-sizing: border-box; margin: 0; padding: 0; }
      body { font-family: Inter, system-ui, -apple-system, sans-serif; -webkit-font-smoothing: antialiased; }
    </style>
  </head>
  <body>
    <div id="root"></div>
    <script type="module" src="/src/main.tsx"></script>
  </body>
</html>
`;
  files.push({ path: 'index.html', description: 'HTML entry point' });

  // Theme tokens (inline enterprise tokens as default)
  const tokensCss = generateTokensCss(theme);
  files.push({ path: 'src/tokens.css', description: `${theme} theme tokens` });

  // Theme data for ThemeProvider
  const themeTs = generateThemeData(theme, kebabName);
  files.push({ path: 'src/theme.ts', description: 'Theme provider data' });

  // Main entry
  const mainTsx = generateMainEntry(name, template);
  files.push({ path: 'src/main.tsx', description: 'React entry point' });

  // Starter page
  const pageTsx = generateStarterPage(template, name);
  files.push({ path: 'src/app.tsx', description: `${template} starter page` });

  // Write all files
  mkdirSync(join(outDir, 'src'), { recursive: true });
  writeFileSync(join(outDir, 'package.json'), JSON.stringify(packageJson, null, 2) + '\n');
  writeFileSync(join(outDir, 'tsconfig.json'), JSON.stringify(tsconfig, null, 2) + '\n');
  writeFileSync(join(outDir, 'vite.config.ts'), viteConfig);
  writeFileSync(join(outDir, 'index.html'), indexHtml);
  writeFileSync(join(outDir, 'src', 'tokens.css'), tokensCss);
  writeFileSync(join(outDir, 'src', 'theme.ts'), themeTs);
  writeFileSync(join(outDir, 'src', 'main.tsx'), mainTsx);
  writeFileSync(join(outDir, 'src', 'app.tsx'), pageTsx);

  return { files, errors };
}

// --- Token CSS generator (enterprise defaults) ---

function generateTokensCss(theme: string): string {
  return `/* Auto-generated by @kailash/prism-compiler scaffold */
/* Theme: ${theme} */

:root {
  --prism-color-interactive-primary: #1E3A5F;
  --prism-color-interactive-primary-hover: #152C49;
  --prism-color-interactive-primary-subtle: #EFF6FF;
  --prism-color-surface-page: #FFFFFF;
  --prism-color-surface-card: #FFFFFF;
  --prism-color-surface-elevated: #F1F5F9;
  --prism-color-surface-error: #FEF2F2;
  --prism-color-surface-success: #F0FDF4;
  --prism-color-text-primary: #0F172A;
  --prism-color-text-secondary: #64748B;
  --prism-color-text-disabled: #94A3B8;
  --prism-color-text-on-primary: #FFFFFF;
  --prism-color-border-default: #E2E8F0;
  --prism-color-border-subtle: #F1F5F9;
  --prism-color-status-error: #DC2626;
  --prism-color-status-success: #16A34A;
  --prism-color-status-warning: #D97706;
  --prism-color-status-info: #2563EB;

  --prism-font-sans: Inter, system-ui, -apple-system, sans-serif;
  --prism-font-mono: JetBrains Mono, Fira Code, Consolas, monospace;
  --prism-font-size-body: 14px;
  --prism-font-size-heading: 24px;
  --prism-font-size-label: 14px;
  --prism-font-size-caption: 12px;

  --prism-radius-sm: 4px;
  --prism-radius-md: 6px;
  --prism-radius-lg: 12px;

  --prism-shadow-sm: 0px 1px 2px 0px rgba(0, 0, 0, 0.05);
  --prism-shadow-md: 0px 4px 6px -1px rgba(0, 0, 0, 0.1);
  --prism-shadow-lg: 0px 10px 15px -3px rgba(0, 0, 0, 0.1);
}
`;
}

// --- Theme data for ThemeProvider ---

function generateThemeData(theme: string, _name: string): string {
  return `import type { ThemeTokenData } from '@kailash/prism-web';

export const themeData: ThemeTokenData = {
  themes: {
    ${theme}: {
      name: '${theme.charAt(0).toUpperCase() + theme.slice(1)}',
      light: {
        '--prism-color-interactive-primary': '#1E3A5F',
        '--prism-color-interactive-primary-hover': '#152C49',
        '--prism-color-interactive-primary-subtle': '#EFF6FF',
        '--prism-color-surface-page': '#FFFFFF',
        '--prism-color-surface-card': '#FFFFFF',
        '--prism-color-surface-elevated': '#F1F5F9',
        '--prism-color-text-primary': '#0F172A',
        '--prism-color-text-secondary': '#64748B',
        '--prism-color-text-disabled': '#94A3B8',
        '--prism-color-text-on-primary': '#FFFFFF',
        '--prism-color-border-default': '#E2E8F0',
        '--prism-color-border-subtle': '#F1F5F9',
        '--prism-color-status-error': '#DC2626',
        '--prism-color-status-success': '#16A34A',
        '--prism-color-status-warning': '#D97706',
        '--prism-color-status-info': '#2563EB',
      },
      dark: {
        '--prism-color-interactive-primary': '#60A5FA',
        '--prism-color-surface-page': '#0F172A',
        '--prism-color-surface-card': '#1E293B',
        '--prism-color-surface-elevated': '#334155',
        '--prism-color-text-primary': '#F8FAFC',
        '--prism-color-text-secondary': '#94A3B8',
        '--prism-color-text-on-primary': '#0F172A',
        '--prism-color-border-default': '#334155',
      },
    },
  },
};
`;
}

// --- Main entry point ---

function generateMainEntry(name: string, _template: string): string {
  return `import { createRoot } from 'react-dom/client';
import { ThemeProvider, LayoutProvider } from '@kailash/prism-web';
import { themeData } from './theme.js';
import { App } from './app.js';

const root = document.getElementById('root');
if (root) {
  createRoot(root).render(
    <ThemeProvider tokens={themeData} defaultMode="system">
      <LayoutProvider>
        <App />
      </LayoutProvider>
    </ThemeProvider>,
  );
}
`;
}

// --- Starter page ---

function generateStarterPage(template: string, name: string): string {
  const templateImport = `${template.charAt(0).toUpperCase() + template.slice(1)}Template`;

  switch (template) {
    case 'dashboard':
      return `import { ${templateImport}, Grid } from '@kailash/prism-web';

export function App() {
  return (
    <${templateImport}
      title="${name}"
      subtitle="Overview"
      statsRow={
        <>
          <StatCard label="Total Users" value="1,234" />
          <StatCard label="Revenue" value="$45,678" />
          <StatCard label="Orders" value="89" />
          <StatCard label="Conversion" value="3.2%" />
        </>
      }
      primaryChart={
        <div style={{ height: 300, display: 'flex', alignItems: 'center', justifyContent: 'center', border: '1px dashed var(--prism-color-border-default)', borderRadius: 8 }}>
          Chart placeholder — replace with your chart library
        </div>
      }
    />
  );
}

function StatCard({ label, value }: { label: string; value: string }) {
  return (
    <div style={{ padding: 16, borderRadius: 8, border: '1px solid var(--prism-color-border-default)', backgroundColor: 'var(--prism-color-surface-card)' }}>
      <div style={{ fontSize: 12, color: 'var(--prism-color-text-secondary)' }}>{label}</div>
      <div style={{ fontSize: 24, fontWeight: 700, color: 'var(--prism-color-text-primary)', marginTop: 4 }}>{value}</div>
    </div>
  );
}
`;

    case 'list':
      return `import { ${templateImport}, DataTable, type ColumnDef } from '@kailash/prism-web';

interface Item { id: number; name: string; status: string; [key: string]: unknown; }

const columns: ColumnDef<Item>[] = [
  { field: 'name', header: 'Name', sortable: true },
  { field: 'status', header: 'Status', sortable: true },
];

const data: Item[] = [
  { id: 1, name: 'Item One', status: 'Active' },
  { id: 2, name: 'Item Two', status: 'Draft' },
  { id: 3, name: 'Item Three', status: 'Active' },
];

export function App() {
  return (
    <${templateImport}
      title="${name}"
      content={
        <DataTable columns={columns} data={data} sorting={{ enabled: true }} pagination={{ enabled: true }} />
      }
    />
  );
}
`;

    case 'conversation':
      return `import { ${templateImport}, ChatEngine, type ChatMessage } from '@kailash/prism-web';

const messages: ChatMessage[] = [
  { id: '1', type: 'assistant', content: 'Hello! How can I help you today?', timestamp: Date.now(), sender: 'assistant' },
];

export function App() {
  return (
    <${templateImport}
      content={
        <ChatEngine
          messages={messages}
          suggestions={[
            { label: 'Help me write', value: 'help me write' },
            { label: 'Analyze data', value: 'analyze data' },
          ]}
          onSend={(msg) => console.log('Send:', msg)}
        />
      }
    />
  );
}
`;

    default:
      return `import { ${templateImport} } from '@kailash/prism-web';

export function App() {
  return (
    <${templateImport}
      title="${name}"
      content={<div style={{ padding: 24 }}>Your content here</div>}
    />
  );
}
`;
  }
}
