/**
 * @kailash/prism-compiler — Web target emitter
 * Generates tailwind.config.ts and CSS custom properties from theme tokens.
 * Spec: docs/specs/02-token-architecture.md § Compilation Targets
 */

import type { ThemeTokens, OutputFile } from './types.js';
import { flattenTokens } from './parse.js';

/**
 * Generate Tailwind config extending the default with Prism tokens.
 */
export function emitTailwindConfig(tokens: ThemeTokens): OutputFile {
  const { primitive, semantic } = tokens.tokens;

  const colors: Record<string, string> = {};
  for (const [name, hex] of Object.entries(primitive.color)) {
    colors[name] = hex;
  }

  // Map semantic colors to CSS custom property references
  const semanticColors: Record<string, string> = {};
  const flatSemantic = flattenTokens(semantic.color as unknown as Record<string, unknown>);
  for (const path of Object.keys(flatSemantic)) {
    const cssVar = `var(--prism-color-${path.replace(/\./g, '-')})`;
    semanticColors[path.replace(/\./g, '-')] = cssVar;
  }

  const spacing: Record<string, string> = {};
  for (const val of primitive.spacing.scale) {
    spacing[String(val)] = `${val / 16}rem`;
  }

  const fontSize: Record<string, [string, Record<string, string>]> = {};
  for (const [name, comp] of Object.entries(semantic.typography)) {
    const typToken = comp as { size: number; line_height: number; weight: number };
    fontSize[name] = [
      `${typToken.size / 16}rem`,
      { lineHeight: String(typToken.line_height), fontWeight: String(typToken.weight) },
    ];
  }

  const borderRadius: Record<string, string> = {};
  for (const val of primitive.radius.scale) {
    if (val === 9999) {
      borderRadius['pill'] = '9999px';
    } else {
      borderRadius[String(val)] = `${val}px`;
    }
  }
  // Add semantic radii
  const flatRadii = flattenTokens(semantic.radius as unknown as Record<string, unknown>);
  for (const [path, val] of Object.entries(flatRadii)) {
    const numVal = typeof val === 'object' && val !== null && 'value' in val
      ? (val as { value: number }).value
      : typeof val === 'number' ? val : undefined;
    if (numVal !== undefined) {
      borderRadius[path.replace(/\./g, '-')] = `${numVal}px`;
    }
  }

  const boxShadow: Record<string, string> = {};
  for (const [name, value] of Object.entries(primitive.shadow)) {
    boxShadow[name] = value;
  }

  const transitionDuration: Record<string, string> = {};
  for (const dur of primitive.motion.durations) {
    transitionDuration[String(dur)] = `${dur}ms`;
  }

  const transitionTimingFunction: Record<string, string> = {};
  for (const [name, value] of Object.entries(primitive.motion.easings)) {
    transitionTimingFunction[name] = value;
  }

  const screens: Record<string, string> = {};
  for (const [name, value] of Object.entries(primitive.breakpoints)) {
    if (value > 0) {
      screens[name] = `${value}px`;
    }
  }

  const fontFamily: Record<string, string[]> = {};
  for (const [name, value] of Object.entries(primitive.typography.families)) {
    fontFamily[name] = value.split(',').map((s: string) => s.trim());
  }

  const config = `// Auto-generated by @kailash/prism-compiler
// Theme: ${tokens.name}
// DO NOT EDIT — regenerate with: npx prism-compile --theme ${tokens.name.toLowerCase().replace(/\s+/g, '-')} --target web

import type { Config } from 'tailwindcss';

const config: Config = {
  content: ['./src/**/*.{ts,tsx,js,jsx}'],
  theme: {
    screens: ${JSON.stringify(screens, null, 4).replace(/^/gm, '    ').trim()},
    extend: {
      colors: ${JSON.stringify({ ...colors, ...semanticColors }, null, 4).replace(/^/gm, '      ').trim()},
      spacing: ${JSON.stringify(spacing, null, 4).replace(/^/gm, '      ').trim()},
      fontSize: ${JSON.stringify(fontSize, null, 4).replace(/^/gm, '      ').trim()},
      fontFamily: ${JSON.stringify(fontFamily, null, 4).replace(/^/gm, '      ').trim()},
      borderRadius: ${JSON.stringify(borderRadius, null, 4).replace(/^/gm, '      ').trim()},
      boxShadow: ${JSON.stringify(boxShadow, null, 4).replace(/^/gm, '      ').trim()},
      transitionDuration: ${JSON.stringify(transitionDuration, null, 4).replace(/^/gm, '      ').trim()},
      transitionTimingFunction: ${JSON.stringify(transitionTimingFunction, null, 4).replace(/^/gm, '      ').trim()},
    },
  },
  plugins: [],
};

export default config;
`;

  return { path: 'tailwind.config.ts', content: config };
}

/**
 * Generate CSS custom properties for all semantic and component tokens.
 * Naming convention: --prism-{tier}-{path} where dots become hyphens.
 */
export function emitCssProperties(tokens: ThemeTokens): OutputFile {
  const lines: string[] = [
    '/* Auto-generated by @kailash/prism-compiler */',
    `/* Theme: ${tokens.name} */`,
    '/* DO NOT EDIT — regenerate with: npx prism-compile --theme enterprise --target web */',
    '',
    ':root {',
  ];

  // Primitive colors as CSS custom properties
  for (const [name, hex] of Object.entries(tokens.tokens.primitive.color)) {
    lines.push(`  --prism-primitive-color-${name}: ${hex};`);
  }
  lines.push('');

  // Semantic color tokens (resolve $primitive references to hex values)
  const primColors = tokens.tokens.primitive.color;
  const flatColors = flattenTokens(tokens.tokens.semantic.color as unknown as Record<string, unknown>);
  for (const [path, val] of Object.entries(flatColors)) {
    const cssName = `--prism-color-${path.replace(/\./g, '-')}`;
    let value = typeof val === 'object' && val !== null && 'value' in val
      ? (val as { value: string }).value
      : typeof val === 'string' ? val : '';
    // Resolve $primitive.color.{name} references
    if (value.startsWith('$primitive.color.')) {
      const colorName = value.replace('$primitive.color.', '');
      value = primColors[colorName] ?? value;
    }
    if (value) {
      lines.push(`  ${cssName}: ${value};`);
    }
  }
  lines.push('');

  // Spacing tokens
  for (const val of tokens.tokens.primitive.spacing.scale) {
    lines.push(`  --prism-spacing-${val}: ${val}px;`);
  }
  lines.push('');

  // Typography tokens
  for (const [name, family] of Object.entries(tokens.tokens.primitive.typography.families)) {
    lines.push(`  --prism-font-${name}: ${family};`);
  }
  lines.push('');

  // Radius tokens
  const flatRadii = flattenTokens(tokens.tokens.semantic.radius as unknown as Record<string, unknown>);
  for (const [path, val] of Object.entries(flatRadii)) {
    const numVal = typeof val === 'object' && val !== null && 'value' in val
      ? (val as { value: number }).value
      : typeof val === 'number' ? val : undefined;
    if (numVal !== undefined) {
      lines.push(`  --prism-radius-${path.replace(/\./g, '-')}: ${numVal}px;`);
    }
  }
  lines.push('');

  // Shadow tokens
  for (const [name, value] of Object.entries(tokens.tokens.primitive.shadow)) {
    lines.push(`  --prism-shadow-${name}: ${value};`);
  }
  lines.push('');

  // Motion tokens
  for (const dur of tokens.tokens.primitive.motion.durations) {
    lines.push(`  --prism-duration-${dur}: ${dur}ms;`);
  }
  for (const [name, value] of Object.entries(tokens.tokens.primitive.motion.easings)) {
    lines.push(`  --prism-easing-${name}: ${value};`);
  }

  lines.push('}');

  // Dark mode overrides
  if (tokens.themes?.dark) {
    lines.push('');
    lines.push('@media (prefers-color-scheme: dark) {');
    lines.push('  :root {');
    const darkColors = tokens.themes.dark.color || {};
    for (const [path, value] of Object.entries(darkColors)) {
      lines.push(`    --prism-color-${path.replace(/\./g, '-')}: ${value};`);
    }
    lines.push('  }');
    lines.push('}');
  }

  lines.push('');

  return { path: 'prism-tokens.css', content: lines.join('\n') };
}

export function compileWeb(tokens: ThemeTokens): OutputFile[] {
  return [emitTailwindConfig(tokens), emitCssProperties(tokens)];
}
